### ISSUE TITLE
Licensing terms.

### ISSUE THREAD

**Issue by SoleCode** [Brunogr/graphql-dynamic-filter-dotnetcore#6]
Hi what is the licensing terms for using your code?

**Comment by SoleCode** [comment]
@Brunogr Can you please let me know?

**Comment by Brunogr** [comment]
@SoleCode thank you for your interest in the code.

It is MIT License, i just updated the project with the file.

**Comment by SoleCode** [comment]
@Brunogr thank you for quick response. This Dynamic Filter project you wrote is really great. Thank you for sharing it with everyone.

**Comment by Brunogr** [comment]
i'm glad it is useful for you! Feel free to contribute or use it anyway you want!
